# ============================================================================== 数据源配置
# 主库数据源（公共数据源配置见 application.properties）
spring.datasource.druid.master.url=jdbc:mysql://8.141.0.77:3306/ry-vue-invoice?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
spring.datasource.druid.master.username=root
spring.datasource.druid.master.password=!QAZ2wsx
# ============================================================================== redis 配置
# 地址
spring.data.redis.host=8.141.0.77
# 端口，默认为6379
spring.data.redis.port=6379
# 数据库索引
spring.data.redis.database=0
# 密码
spring.data.redis.password=Luoge@2024
